import react from "@vitejs/plugin-react"
import { defineConfig, type Plugin } from "vite"

const virtualModuleId = "virtual:douyin-skill-repository"
const resolvedVirtualModuleId = `\0${virtualModuleId}`

function skillRepositoryPlugin(): Plugin {
  return {
    name: "douyin-skill-repository",
    resolveId(id) {
      return id === virtualModuleId ? resolvedVirtualModuleId : null
    },
    load(id) {
      if (id !== resolvedVirtualModuleId) return null
      const payload = {
        version: "unpublished-seed",
        updatedAt: new Date().toISOString(),
        packagePath: "",
        name: "douyin-writing-skills",
        skills: [],
        runtimeFiles: {
          "SKILL.md": "# Douyin Writing Skills\n\nThis runtime is generated by the workbench and published to the configured Skill repository.\n",
          "references/skills.json": `${JSON.stringify({ name: "douyin-writing-skills", version: "unpublished-seed", skills: [] }, null, 2)}\n`,
          "references/research-playbook.md": "# Research Playbook\n\nUse verified facts, avoid fabricating sources, and respect the skill risk boundaries.\n",
        },
      }
      return `export default ${JSON.stringify(payload)}`
    },
  }
}

export default defineConfig({
  plugins: [react(), skillRepositoryPlugin()],
})
